<a href="https://colab.research.google.com/github/suganyamuralikarthik/Python-Data-Analysis-with-NumPy-and-Pandas/blob/main/Np_n_pd_ass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python DA Assignment 1—Numpy and Pandas**

**Tasks**  
**Numpy Array Operations**

**1. Create a 1D NumPy Array:  
Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:  
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]**

In [5]:
import numpy as np
import pandas as pd

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

**2. Inspection and Properties:  
 Inspect the shape, data type, and the number of elements in the array. Inspect
the shape of the temperatures_w1 array.**


In [ ]:
print("shape:",temperatures_w1.shape)
print("datatype:",temperatures_w1.dtype)
print("size:",temperatures_w1.size)

shape: (7,)
datatype: float64
size: 7


**3. Array Operations:**

   

*  **Convert the temperatures_w1 from Celsius to Fahrenheit using the formula
Fahrenheit = (Celsius * 9/5) + 32**
* **Find the maximum, minimum, and mean temperatures for the week.**


  


In [ ]:
temperatures_f = (temperatures_w1*9/5)+32
temperatures_f

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [ ]:
print("Fahrenheit:",temperatures_f)
print("maximum_temp:",temperatures_w1.max())
print("minimum_temp:",temperatures_w1.min())
print("Avg_temp:",temperatures_w1.mean())

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
maximum_temp: 26.1
minimum_temp: 20.8
Avg_temp: 23.542857142857144


**4. Array Slicing and Indexing:**

*   **Extract the temperatures for the first three days of the week.**
* **Extract the temperatures for the weekend (last two days).**
* **Extract the temperatures for the middle three days of the week.**





In [ ]:
first_3_temp = temperatures_w1[0:3]
first_3_temp

array([22.5, 25.3, 20.8])

In [ ]:
weekend_temp = temperatures_w1[-2:]
weekend_temp

array([24.8, 21.9])

In [ ]:
mid_3_temp = temperatures_w1[2:5]
mid_3_temp

array([20.8, 23.4, 26.1])

**5. Create a 2D Array:  
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:  
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)  
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)**  

In [ ]:
temperatures = np.array([
     [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
     [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
     ])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

**6. Inspect and Slice the 2D Array:**
*  **Inspect and print the shape, data type, and total number of elements in the temperatures array.**
*  **Extract the temperatures for each week and the weekends (last two days) for both weeks.**

In [ ]:
print("2D_shape:",temperatures.shape)
print("2D_datatype:",temperatures.dtype)
print("2D_size:",temperatures.size)

2D_shape: (2, 7)
2D_datatype: float64
2D_size: 14


In [ ]:
week1= temperatures[0]
week1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
week2= temperatures[1]
week2

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [ ]:
weekend = temperatures[1,-2:]
weekend

array([22.8, 20.1])

**Pandas Series**

**1. Creating Pandas Series:**
* **Create a Pandas Series named marks with the following data:**

 ➢ **Marks: 95, 92, 89, 85, 80**

 ➢ **Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'**

In [ ]:
marks = pd.Series([95,92,89,85,80],
index = ['Rank1','Rank2','Rank3','Rank4','Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


**2. Indexing and Slicing**

 1.Use the integer index position to access the mark of the 1st rank student.  

In [ ]:
print("Rank1:",marks.iloc[0])

Rank1: 95


* Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.



In [ ]:
print("Top3:\n",marks.loc[['Rank1','Rank2','Rank3']])

Top3:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64


* Use the iloc accessor to retrieve the mark of the 3rd-ranked student.  



In [ ]:
print("Rank3:",marks.iloc[2])

Rank3: 89


* Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.  




In [ ]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


 **3. Manipulating Series**

* Modify the mark of the student with the 1st rank to 100.



In [ ]:
marks['Rank1'] = 100
marks

,0
Rank1,100
Rank2,92
Rank3,89
Rank4,85
Rank5,80


* Remove the entry corresponding to the last rank from the Series



In [ ]:
Remove = marks.drop(['Rank5'])
Remove

,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85


* Compute the CGPA by dividing each mark in the Series by 10.



In [ ]:
CGPA = marks*0.1
CGPA

,0
Rank1,9.5
Rank2,9.2
Rank3,8.9
Rank4,8.5
Rank5,8.0


**Pandas DataFrame**

1. Creating Pandas DataFrame:

➢Create a Pandas DataFrame named transactions with the following data:

➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110  
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'  
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'  
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400  

In [6]:
Transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
            'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                  'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'],
                 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]

})
Transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


**2. Data Exploration**

* Display the transactions DataFrame and its basic information, including head, tail,shape, column names, and data types.  



In [ ]:
Transactions.head()

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [ ]:
Transactions.tail()

,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [ ]:
print("shape:",Transactions.shape)
print("colums:",Transactions.columns)
print("datatype:",Transactions.dtypes)

shape: (10, 4)
colums: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
datatype: TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


* Display only the 'ProductCategory' and 'Amount' columns.



In [7]:
print(Transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400




* Retrieve the last 3 columns of the DataFrame using iloc or loc.  


In [8]:
print(Transactions.iloc[:,1:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400




* Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.



In [10]:
print(Transactions[(Transactions['Region']== 'North') & (Transactions['Amount']>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400




* Find the value counts for the 'ProductCategory' column.  



In [12]:
print(Transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64




* Find the unique values in the 'Region' column.


In [15]:
Transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)



* Group by 'Region' and find the mean amount for each region.  



In [17]:
Transactions.groupby('Region')['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


**3. Manipulating the DataFrame**



* Modify the 'Amount' for the transaction with TransactionID 102 to 165.



In [33]:
Transactions.loc[Transactions['TransactionID'] == 102, 'Amount'] = 165
print(Transactions[Transactions["TransactionID"] == 102])

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165




* Add a new column 'Discount' by calculating 10% of the 'Amount'.



In [48]:
Transactions['Discount']=Transactions['Amount']*0.10
print(Transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0




* Remove the row with TransactionID 109.



In [45]:
Transactions.drop(Transactions[Transactions['TransactionID']==109].index)

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0




* Delete the 'Discount' column from the DataFrame.



In [49]:
Transactions.drop("Discount",axis=1,inplace=True)
print(Transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
